### ISSUE TITLE
缺少函数实现 

### ISSUE THREAD

**Issue by syswyl** [shaoshengsong/YOLOv5-ShuffleNetV2#2]
作者您好，在使用您的代码时候，我想测试shufflenetv2的效果，但在您的yaml文件的backbone中将第一层改为了
` [[-1, 1, conv_bn_act_maxpool, [3]],    # 0-P2/4`

在common.py中并没有找到**conv_bn_act_maxpool**的实现，不知道您这个模块具体是什么含义。
期待您的回复

**Comment by shaoshengsong** [comment]
因为shufflenetv2开始的结构是
    (0): Conv2d
    (1): BatchNorm2d
    (2): ReLU
    (3): MaxPool2d
所以直接改成了
conv_bn_relu_maxpool，可以把yaml文件中的conv_bn_act_maxpool改成conv_bn_relu_maxpool

**Comment by syswyl** [comment]
@shaoshengsong  我已经在您的函数实现中发现并且修改了， 谢谢您的回复~

**Comment by ljh2665740846** [comment]
作者你好我今天改好权重加了数据集COCO运行后遇到的问题是：AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from 'C:\\Users\\86188\\Desktop\\yolo\\YOLOv5-ShuffleNetV2-main\\models\\common.py'>
我不知道怎么解决，希望您可以帮忙解答下。

**Comment by syswyl** [comment]
> 作者你好我今天改好权重加了数据集COCO运行后遇到的问题是：AttributeError: Can't get attribute 'SPPF' on <module 'models.common' from 'C:\Users\86188\Desktop\yolo\YOLOv5-ShuffleNetV2-main\models\common.py'>
> 我不知道怎么解决，希望您可以帮忙解答下。

也就是相应的实现函数找不到 去官方models看看有没有对应的，添加到这边就好了

**Comment by ljh2665740846** [comment]
问题解决了，更换相应版本的yolov5s.pt 文件更改好参数就行了，谢谢作者

**Comment by PraveenMNaik** [comment]
Dear Author, Got below error: Can you solve it- run on Colab ....please try from your end too
Traceback (most recent call last):
  File "/content/YOLOv5-ShuffleNetV2/train.py", line 543, in <module>
    train(hyp, opt, device, tb_writer)
  File "/content/YOLOv5-ShuffleNetV2/train.py", line 189, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/content/YOLOv5-ShuffleNetV2/utils/datasets.py", line 63, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/content/YOLOv5-ShuffleNetV2/utils/datasets.py", line 385, in __init__
    cache, exists = torch.load(cache_path), True  # load
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str
